# -*- coding: utf-8 -*-
"""Copy of ShAI_BootCamp_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ETtDuHnLsvWTBX9c8-54pOUpE2JtSS1

#About Dataset
salaries dataset generally provides information about the employees of an organization in relation to their compensation. It typically includes details such as how much each employee is paid (their salary), their job titles, the departments they work in, and possibly additional information like their level of experience, education, and employment history within the organization.

# Features
- 'Id'
- 'EmployeeName'
- 'JobTitle'
- 'BasePay'
- 'OvertimePay'
- 'OtherPay'
- 'Benefits'
- 'TotalPay' -> salary
- 'TotalPayBenefits'
- 'Year'
- 'Notes'
- 'Agency'
- 'Status'

# Tasks

1. **Basic Data Exploration**: Identify the number of rows and columns in the dataset, determine the data types of each column, and check for missing values in each column.

2. **Descriptive Statistics**: Calculate basic statistics mean, median, mode, minimum, and maximum salary, determine the range of salaries, and find the standard deviation.

3. **Data Cleaning**: Handle missing data by suitable method with explain why you use it.

4. **Basic Data Visualization**: Create histograms or bar charts to visualize the distribution of salaries, and use pie charts to represent the proportion of employees in different departments.

5. **Grouped Analysis**: Group the data by one or more columns and calculate summary statistics for each group, and compare the average salaries across different groups.

6. **Simple Correlation Analysis**: Identify any correlation between salary and another numerical column, and plot a scatter plot to visualize the relationship.

8. **Summary of Insights**: Write a brief report summarizing the findings and insights from the analyses.

# Very Important Note
There is no fixed or singular solution for this assignment, so if anything is not clear, please do what you understand and provide an explanation.
"""

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/content/Salaries.csv')
df.head()

df.columns

#---------- Identify the number of rows and columns in the dataset
rows=len(df.axes[0])
columns=len(df.axes[1])
print("the number of rows = ",rows)
print("the number of columns = ",columns)
#---determine the data types of each column
df.dtypes
#------check for missing values in each column.
df.isnull()

#------mean, median, mode, minimum, and maximum salary
df['TotalPay'].mean()
df['TotalPay'].median()
df['TotalPay'].mode()
mn=df['TotalPay'].min()
mx=df['TotalPay'].max()
print("the minimum ",mn)
print("the maximum ",mx)
#------determine the range of salaries
#avg=df['BasePay'].sum()/df['BasePay'].count() this code for finding thr average.....sorry...
print("the range is ",mx-mn)
#-----find the standard deviation.
sd=np.std(df['TotalPay'])
print("the standard deviation ",sd)

#I opened the salaries file Status and Notes columns are empty so we can clean the data set by deleting them
df=df.drop(columns=["Notes","Status"])
#Benefits column has missing values so we can fill them by zeros
df["Benefits"].fillna(0,inplace=True)
#the data set is huge so i can't determin if we have a duplicate rows so i will apply this line of code to ensure that the duplicates removed
df.drop_duplicates(inplace=True)

#df.head()
columns=list(df.columns)
print(columns)

df.hist(column='TotalPay',color='orange')

#df.groupby(["JobTitle"]).sum().plot(kind='pie',y='EmployeeName')
#I'm still facing an error with this line of code

group_=df.groupby(['JobTitle'])
group_.head()
stats=group_.agg({'Year':['mean','sum']})
print(stats)
avg=group_.agg({'TotalPay':['mean']})
print(avg)

import seaborn as sns
corr_=df['TotalPay'].corr(df['TotalPayBenefits'])
graph_=sns.scatterplot(x='TotalPay',y='TotalPayBenefits',data=df)
graph_.set_title("salary vs total")

"""# Good Luck!"""